-- Move workout plans to a single JSON `structure` column and drop the
-- relational exercise/day tables. The app is now AI-first: plans (and their
-- free-text exercises) are generated by the LLM or typed by the user, so the
-- curated exercise library and the day/exercise join tables are no longer used.
--
-- Existing plans are cleared (pre-launch, no migration needed).

-- 1) Detach any current-plan references so the plans can be cleared.
update public.user_settings
set current_plan_id = null,
    current_plan_start_date = null
where current_plan_id is not null;

-- 2) Add the JSON structure column (holds days + free-text exercises).
alter table public.workout_plans
  add column if not exists structure jsonb not null default '{"days": []}'::jsonb;

-- 3) Clear existing plans — their relational days/exercises are being dropped.
delete from public.workout_plans;

-- 4) Drop the now-unused relational tables.
drop table if exists public.plan_exercises cascade;
drop table if exists public.workout_days cascade;
drop table if exists public.exercises cascade;
